let Name = "Jeffrey Dahmer";
console.log("Name: " + Name);
let Height = "6 ft";
console.log("Height:" + Height);
let Power = 560;
console.log("Power:" + Power);
let HP = 5000;
console.log("HP:" + HP);
let Speed = 20;
console.log("Speed:" + Speed);
let Cursed = true;
console.log("Cursed:" + Cursed);
let Sneak = 34;
console.log("Sneak:" + Sneak);
let Luck = -50;
console.log("Luck:" + Luck);
let Pride = 100;
console.log("Pride:" + Pride);
let Mana = 500;
console.log("Mana:" + Mana);